# Generated by Django 5.0.7 on 2024-07-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discount_price',
            new_name='discounted_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CP', 'Capsicum'), ('CR', 'Carrot'), ('CF', 'Cauliflower'), ('CL', 'Corianderleaves'), ('BW', 'Babywipes'), ('BA', 'Babywipes'), ('ML', 'milk'), ('CL', 'Corianderleaves'), ('BW', 'Babywipes'), ('BA', 'Babywipes')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(upload_to='products'),
        ),
    ]
