# Generated by Django 5.0.7 on 2024-07-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('VG', 'Vegitables'), ('FR', 'Fruits'), ('GH', 'Ghee'), ('CD', 'Curd'), ('IC', 'icecreams'), ('HM', 'Home and Kitchen'), ('ML', 'milk'), ('SS', 'Snacks Store'), ('CH', 'Cleaning & Household'), ('DS', 'Daily Staples'), ('BS', 'Beverages'), ('BH', 'beauty and hygiene')], max_length=2),
        ),
    ]
