# Generated by Django 5.0.7 on 2024-07-16 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_customer_state_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('KARNATAKA', 'KARNATAKA'), ('TAMILNADU', 'TAMILNADU'), ('KERALA', 'KERALA'), ('GOA', 'GOA')], max_length=100),
        ),
    ]
