# Generated by Django 5.0.7 on 2024-07-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_state_productvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('TAMILNADU', 'TAMILNADU'), ('GOA', 'GOA'), ('KARNATAKA', 'KARNATAKA'), ('KERALA', 'KERALA')], max_length=100),
        ),
    ]
